name: Node build

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu:latest
    strategy:
      matrix: [12]
    name: Node ${{ matrix.node }}
  steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

