name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Approve to run
        options:
          - approve
      message:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.name == 'approve' }}
    strategy:
      matrix:
        node-version: [10.x,]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
