name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: Running reusable
        uses: ./.github/workflow/re-usable.yaml@main

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x,]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
